### ISSUE TITLE
感谢老王,建议每个版本创建一个release这样我就不用一下子都下载下来了

### ISSUE THREAD

**Issue by ExileZhu** [wangvpn666/wangvpn#15]

**Comment by GamerNoTitle** [comment]
其实你可以直接点击你想要下载的文件，进去以后点右上角的RAW来下载，如果你用git clone的话你就要把整个老王的库下载下来，文件体积太大了

**Comment by maolaila** [comment]
期待老王更新

**Comment by ExileZhu** [comment]
> 其实你可以直接点击你想要下载的文件，进去以后点右上角的RAW来下载，如果你用git clone的话你就要把整个老王的库下载下来，文件体积太大了

好的 谢谢
