### ISSUE TITLE
v2.2.11，PC连接码始终获取失败；发送邮件给老王的按钮没反应；捐赠始终提示失败（本人特想捐赠）；英文版有很多语法错误（这个可以理解）。华为 nova 4e，EMUI 10，Android 10.

### ISSUE THREAD

**Issue by SamToki** [wangvpn666/wangvpn#16]

**Comment by GamerNoTitle** [comment]
PC连线码现在停止供应了呀 你如果升级到最新版本你会发现连连线码这个界面都没了
老王的邮箱是wangvpn666.tech@gmail.com，你可以直接发邮件到这里
捐赠我就不清楚了

**Comment by SamToki** [comment]
了解

**Comment by GamerNoTitle** [comment]
> 了解。如今已用上Express（手动滑稽

Express国内还能用嘛……我怎么连不上……

**Comment by SamToki** [comment]
> 
> 
> > 了解。如今已用上Express（手动滑稽
> 
> Express国内还能用嘛……我怎么连不上……

能用的，先用老王访问官网（不稳定，多试几次），然后从官网下载客户端就行（低调

**Comment by GamerNoTitle** [comment]
> > > 了解。如今已用上Express（手动滑稽
> > 
> > 
> > Express国内还能用嘛……我怎么连不上……
> 
> 能用的，先用老王访问官网（不稳定，多试几次），然后从官网下载客户端就行（低调

好的 我再去试试
