### ISSUE TITLE
老王，google商店找不到你的应用了

### ISSUE THREAD

**Issue by Ypig** [wangvpn666/wangvpn#2]
是不是被下架了啊啊啊，老王，怎么办

额，问一下老王，可以直接去repo里拿你的安装包吗，哈哈

**Comment by wangvpn666** [comment]
> 是不是被下架了啊啊啊，老王，怎么办
> 
> 额，问一下老王，可以直接去repo里拿你的安装包吗，哈哈

兄弟 我这边看没下架呀 安装包你直接拿没关系的 
老王爱你

**Comment by Ypig** [comment]
啊ok，谢谢老王，新版真好玩哦

**Comment by wangvpn666** [comment]
https://github.com/wangvpn666/wangvpn/raw/master/WangVPN_27.apk

这是最新版连结喔


谢谢

Ypig <notifications@github.com>於 2019年4月16日 週二，下午7:28寫道：

**Comment by sdyy86** [comment]
老王啊，有苹果版的不啊

**Comment by wangvpn666** [comment]
谢谢来信
因为谷歌方政策严格
老王先把公开教学取消
现在正在与谷歌积极沟通
之后还会推出
如不这么做 老王随时会被停用
谢谢理解
By嫩妹

sdyy86 <notifications@github.com> 於 2019年6月24日 週一 下午6:50 寫道：
